[project]
name = "automation-backend"
version = "0.1.0"
description = "Backend API for URL analysis automation"
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "sqlmodel>=0.0.24",
    "python-dotenv>=1.0.0",
    "pandas>=2.0.3",
]

